### ISSUE TITLE
Pluggable action interpreters

### ISSUE THREAD

**Issue by jsccast** [Comcast/rulio#4]
Currently an action is either Javascript (with some environment that includes various custom functions) or an action executor request specification.  A rule's action `endpoint` property (which is poorly named) determines whether the action is interpreted as Javascript (`endpoint: "javascript"`) or as an action executor request (targeting the given endpoint).

We should generalize things to allow for pluggable, custom action interpreters.  Say we support an `interpreter` property for an action.  If the `interpreter` for an action is `"javascript"`, then the action is interpreted as if `endpoint: "javascript"` in the current implementation.  If the `intepreter` is `"actionExecutorRequest"`, then the action is interpreter as such.  If the `interpreter` is something else, then the system looks up an application-provided interpreter with that name.  As a crazy example: `interpreter: "bash"`.  Write your own DSLs.

(Maybe also pay attention to an optional `interpreterVersion` property?

An interpreter might look something like

```Go
type ActionInterpreter interface {
        Interpret(ctx *Context, spec interface{}, bs Bindings, env map[string]interface{}, ... ) (interface{}, error)
}
```

Also provide a registry for interpreters so that the runtime could attempt to find the right interpreter for a given rule action.

Then applications could provide any sort of wild action language they desired.

**Comment by boriwo** [comment]
Combine that with a growing library of parameterized (or shall we say "templatized") code snippets for different interpreters...

**Comment by jsccast** [comment]
Merged `actioninterpreters` branch into `master`.
