### ISSUE TITLE
POST response status code is not acted on for external fact requests

### ISSUE THREAD

**Issue by decibelcooper** [Comcast/rulio#53]
The following function is used to perform external fact POST requests:
https://github.com/Comcast/rulio/blob/54befe498aa13ff976ca65c7404e4aa8df4dcbb5/core/http.go#L387-L395

Since the result status code is not used anywhere within this function or the functions it calls, and since it is not propagated to the calling function, there is no information available to event processing about unexpected/unwanted status codes.

I propose defining a fixed set of status codes for external fact requests, and handling them either in the above function or in the calling function:
https://github.com/Comcast/rulio/blob/54befe498aa13ff976ca65c7404e4aa8df4dcbb5/core/query.go#L376-L404

This could be as simple as (pseudocode) `status == 200 ? 👍  : 👎 `

**Comment by decibelcooper** [comment]
FYI I would be happy to create a PR for this.  But of course I want to run this by the maintainers first.

**Comment by jsccast** [comment]
Good point. The very simple approach you suggest sounds good. As it stands, we are somewhat limited in our ability to handle bad fact responses, so happy/sad analysis might be sufficient. A PR would be great.
