### ISSUE TITLE
Inject special variables earlier so that condition code can use them

### ISSUE THREAD

**Issue by jsccast** [Comcast/rulio#6]
Currently some special variables like `event` and `location` are injected (if there's no conflict) into an action's Javascript environment.  Should inject these bindings earlier so that a `code` condition can use these bindings.

Fix should be easy.  See `EvalRuleCondition.Do()` in `core/events.go`.  Move the binding code up a little.

**Comment by wingdog** [comment]
Good timing,  I have a rule that can use this feature.
