### ISSUE TITLE
cache Rules in State implementations for performance increases

### ISSUE THREAD

**Issue by raidancampbell** [Comcast/rulio#76]
A couple things worth mentioning before diving in:
 - I'm woefully unfamiliar with the internal semantics of Rulio
 - I have a patch that implements this and it appears to be working for my needs, but I don't use many features in this area of the codebase so it may be buggy

When searching for matching rules, an internal type `Map` [is returned](https://github.com/Comcast/rulio/blob/master/core/location.go#L657).  `Map` ultimately resolves to `map[string]interface{}`.  Fine, not a problem.  The problem comes later: any rule containing a `code` block will use a custom JSON unmarshaler.  This occurs on each event execution, causing a fair amount of JSON unmarshalings/javascript compilations.  The callstack that does this is below:
 - CleanRule's UnmarshalJSON https://github.com/Comcast/rulio/blob/master/core/rules.go#L113
 - GenericQuery's UnmarshalJSON https://github.com/Comcast/rulio/blob/master/core/query.go#L830
 - ParseQuery calls CodeQueryFromMap https://github.com/Comcast/rulio/blob/master/core/query.go#L765
 - CodeQueryFromMap will compile the javascript https://github.com/Comcast/rulio/blob/master/core/query.go#L342

What I'm playing with is changing the [`state` interface](https://github.com/Comcast/rulio/blob/master/core/state.go#L41) to return `map[string]*Rule`.  Both state implementations would add a `map[string]*Rule` cache to their structs.  During calls to `FindRules` any matched rule would check the cache to see if it's already been instantiated into a `Rule`: return from cache if it exists, otherwise instantiate and add it to the cache.

After typing this all up, I'm realizing it's not the clearest thing, so let me know if you just want to see a PR.

**Comment by jsccast** [comment]
Sounds like good optimization. It's hard to know (at least for me) what the unintended consequences would be. Some of that grotesque marshaling and unmarshaling was IIRC to avoid running into native objects in certain situations. But those concerns could easily either be moot or misplaced.

Thoughts from others?
